[package]
name = "wasi-headers"
version = "0.0.0"
authors = ["Dan Gohman <sunfish@mozilla.com>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
clap = "2"
heck = "0.3.1"
witx = "0.5.0"
